chore: Refactor for pr.go cmd
jenkins-x-plugins/jx-updatebot pull request #103
Opened 2024-12-20 15:16 UTC by GavinPJK

As suggested by @msvticket, refactor code for `cmd/pr/pr.go` before introducing additional features.

2024-12-20 15:16 UTC, GavinPJK commented
/cc @msvticket

2024-12-20 15:39 UTC, msvticket requested changes

2024-12-20 15:39 UTC, msvticket commented on pkg/cmd/pr/pr.go
> -			}
By removing this code you remove the functionality of reusing an existing open pull request. Please add it back.

2024-12-20 15:42 UTC, msvticket commented
Not that it matters that much, but https://www.conventionalcommits.org/ (and our code) defines the distinct commit type `refactor` that is more fitting than `chore` in this case.

2025-01-14 11:27 UTC, msvticket requested changes

2025-01-14 11:27 UTC, msvticket commented on pkg/cmd/pr/pr.go
> +func (o *Options) CreatePullRequests(rule v1alpha1.Rule, labels []string, automerge bool) ([]*scm.PullRequest, error) {
The name and documentation of the method isn't correct now when the reuse functionality has been added. Please fix that.

Why is the method returning []*scm.PullRequest? The value is ignored...

2025-01-14 11:50 UTC, GavinPJK commented on pkg/cmd/pr/pr.go
> +func (o *Options) CreatePullRequests(rule v1alpha1.Rule, labels []string, automerge bool) ([]*scm.PullRequest, error) {
Fixed - renamed to `CreateOrReusePullRequests` and removed returning of `[]*scm.PullRequest`

2025-01-14 12:10 UTC, msvticket commented
/ok-to-test

2025-01-14 12:12 UTC, msvticket requested changes
Please squash the commits and change the scope in the commit message to "refactor".

2025-01-14 15:02 UTC, msvticket requested changes
Also clean up the body of the commit message

2025-01-15 10:00 UTC, GavinPJK commented
/test lint

2025-01-15 11:38 UTC, GavinPJK commented on pkg/cmd/pr/pr.go
> +		{
Done.

2025-01-15 11:44 UTC, msvticket requested changes
Clean the body of the commit. Your path to end up with the commit is irrelevant and confusing to the reader of the commit message.

2025-01-15 12:11 UTC, msvticket requested changes
The body of the commit is still not relevant: 

```
fix: re-add ReusePullRequest logic

fix: sort import

chore: rename CreateOrReusePullRequests

fix: lint

fix: add version and if statements into SetCommitDetails

fix: add version and if statements into SetCommitDetails

fix: pass tests
```

2025-01-15 13:24 UTC, GavinPJK commented
> The body of the commit message is still not relevant:
> 
> ```
> fix: re-add ReusePullRequest logic
> 
> fix: sort import
> 
> chore: rename CreateOrReusePullRequests
> 
> fix: lint
> 
> fix: add version and if statements into SetCommitDetails
> 
> fix: add version and if statements into SetCommitDetails
> 
> fix: pass tests
> ```

fixed

2025-01-15 13:28 UTC, msvticket commented
/approve

2025-01-15 13:29 UTC, merged